[package]
name = "nebel_chess_engine"
version = "0.1.0"
edition = "2021"

# use codegen-units  compile flag optimization

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { version = "1.5.3" }
rand = "0.8"