[package]
name = "cadabra"
version = "0.1.0"
authors = ["Joachim Enggård Nebel"]
edition = "2021"

[build]
RUSTFLAGS = "-C target-cpu=native, codegen-units=1"
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#cadabra = { path = "../cadabra" }
rayon = { version = "1.5.3" }
rand = "0.8"