[package]
name = "cadabra"
version = "0.1.0"
edition = "2021"

[build]
RUSTFLAGS = "-C target-cpu=native, codegen-units=1"

[profile.test]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { version = "1.5.3" }
rand = "0.8"