[package]
name = "cadabra"
version = "0.1.0"
authors = ["Joachim Enggård Nebel"]
edition = "2021"
license-file = "LICENSE.txt"
build = "./prepare_constants.rs"

[dependencies]
bitintr = "0.3.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "perft_bench"
harness = false