[package]
name = "nebel_chess_engine"
version = "0.1.0"
edition = "2021"

[build]
target = "native"
RUSTFLAGS = "-C link-args=-Wl,-zstack-size=4194304"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitintr = { version = "0.3.0" }