[package]
name = "cadabra"
version = "0.2.0"
authors = ["Joachim Enggård Nebel"]
edition = "2021"
license-file = "BSD-2-Clause"
build = "prepare_constants.rs"
description = "UCI compatible chess engine"
repository = "https://github.com/JENebel/Cadabra/"  
default-run = "cadabra"

[[bin]]
name = "validator"
path = "validator/main.rs"

[[bin]]
name = "cadabra"
path = "src/main.rs"

[dependencies]
bitintr = "0.3.0"
colored = "2.0.0"