[build]
rustflags = ["-Ctarget-cpu=native"]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1

[alias]
validate = "run --bin validator stockfish"
benchmark = "run --release bench"
dev_benchmark = "run bench"