[build]
rustflags = ["-Ctarget-cpu=native"]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
#debug = true

[alias]
validate = "test validate_move_gen -- --ignored"
benchmark = "run --release bench"
dev_benchmark = "run bench"